/**
 * The ergonomics batch B4 (pure move) — the human-facing question UI: the E3 project
 * trust gate (ADR-0037), the mcp/skills env merges, the W21 approval
 * panel (askPanel — the bounded block, the verdict mapping lives in
 * chat.ts), the don't-ask-again rule writer, and the uncertain-execution
 * decisions. All bodies moved verbatim from index.ts.
 */

import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, symlinkSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { projectTrustRows, projectTrustView, projectUntrustedNote, uncertainView, type PanelVerdict, type PanelView } from "@vincemakes/kiso-tui";
import { projectArtifacts, recordTrust, trustFor, type ProjectArtifacts } from "@vincemakes/kiso-runtime";
import type { AgentSession, KisoExtension } from "@vincemakes/kiso-runtime";
import { bodyLog, currentAgentExtensions, dock, extensionsDir, kisoHome, mergedTempPaths, type LineInput } from "./state.js";
import { loadUserConfig, resolveProjectTrustPolicy } from "./config.js";
import { getMode } from "./mode.js";

/**
 * W21 — ask the human with the approval panel: the bounded block that
 * replaces the running tool's live window while the approval is pending.
 * The editor owns the keys (the digits/tab/esc/enter routing, the rule
 * input, the tab-amend); the compositor renders the block + the leads;
 * the CLI maps the verdict (the bare-No abort, the No+words tool_result,
 * the allow-amend words riding the next turn — all live in chat.ts,
 * never here).
 *
 * Non-interactive stdin (piped, CI) cannot wait forever: the approval
 * AUTO-DENIES, printed loudly — never silently ignored, never hung
 * (Area 7). A TTY without a dock (rows < 4) falls back to the v2a line
 * question (y/n → allow/deny) — the panel cannot render without the
 * dock's live region.
 *
 * rounds 8/10: the ask is ABORTABLE — registered in `pendingAsk`, the
 * SIGINT handler resolves it with { action: "cancel" } (the panel closes
 * through the editor's panelCancel, the dock-less question through
 * cancelQuestion). The dock-less question callback is NOT left dangling:
 * an input that arrives after the cancellation is re-emitted as a fresh
 * "line" — it becomes the next user turn instead of being swallowed by
 * the dead question.
 */
export let pendingAsk: (() => void) | null = null;
export function askPanel(input: LineInput, view: PanelView): Promise<PanelVerdict> {
	if (!process.stdin.isTTY) {
		console.log(`[non-interactive — no human to ask: ${view.fallbackQuestion}]`);
		return Promise.resolve({ action: "deny", reason: "no human to ask" });
	}
	return new Promise((resolve) => {
		let settled = false;
		pendingAsk = () => {
			if (settled) return;
			settled = true;
			pendingAsk = null;
			if (dock.active) input.panelCancel();
			else input.cancelQuestion();
			resolve({ action: "cancel" });
		};
		if (dock.active) {
			input.panelAsk(view, (verdict) => {
				if (settled) return; // a cancelled panel's late commit is dead
				settled = true;
				pendingAsk = null;
				resolve(verdict);
			});
		} else {
			// v2c: a TTY without a dock (rows < 4) — the fallback question
			// in the body; the y/n line answer maps to the verdicts.
			bodyLog(view.fallbackQuestion);
			input.question(view.fallbackQuestion, (answer) => {
				if (settled) {
					// The question was cancelled; this line is a NEW user turn.
					input.emitLine(answer);
					return;
				}
				settled = true;
				pendingAsk = null;
				const yes = answer.trim().toLowerCase().startsWith("y");
				resolve(yes ? { action: "allow", reason: "" } : { action: "deny", reason: "" });
			});
		}
	});
}

/**
 * W21/R3 — the "2 Yes, don't ask again for <tool>" rule: a GENERATED
 * extension, ALLOW-ONLY by construction (it never emits deny or ask —
 * the mode moat and the safe-defaults moat keep their teeth). The file
 * is HUMAN-EDITABLE and HUMAN-DELETABLE — that IS the revocation path.
 * The loader sorts *.mjs alphabetically, so dont-ask-again.mjs binds
 * BEFORE safe-defaults.mjs: the allow is the chain's first word, the
 * safe-defaults deny moat still wins (deny > allow — the R3 order).
 */
export async function addDontAskAgainRule(rule: string): Promise<void> {
	const dir = extensionsDir();
	const file = join(dir, "dont-ask-again.mjs");
	const existed = existsSync(file);
	const module = [
		"// generated by kiso — the \"2 Yes, don't ask again for <tool>\" rule.",
		"// HUMAN-EDITABLE and HUMAN-DELETABLE — this file IS the revocation path:",
		"// delete a rule from the set (or the whole file) to be asked again.",
		"// ALLOW-ONLY by design (R3): never emits deny or ask — the mode moat",
		"// and the safe-defaults moat keep their teeth.",
		`export const RULES = new Set(${JSON.stringify([rule])});`,
		"",
		"export default {",
		'  name: "dont-ask-again",',
		"  approvals: [",
		"    {",
		"      decide(call) {",
		'        return RULES.has(call.name) ? { action: "allow" } : { action: "abstain" };',
		"      },",
		"    },",
		"  ],",
		"};",
		"",
	].join("\n");
	mkdirSync(dir, { recursive: true });
	writeFileSync(file, module, "utf8");
	// The live in-session effect: a file that existed at startup was
	// imported by the loader — ONE namespace — so mutating the exported
	// RULES Set is live NOW (the current run's chain reads the same Set).
	const mod = (await import(pathToFileURL(file).href)) as { RULES?: Set<string>; default?: unknown };
	if (mod.RULES !== undefined && !mod.RULES.has(rule)) mod.RULES.add(rule);
	// A FIRST-time rule (a file that did not exist at startup) is not yet
	// in the current run's chain — the chain is fixed at a run's start —
	// so the generated extension joins the NEXT run's policies (run.ts
	// re-reads the session config's extensions array, shared by
	// reference). The honest story: a new rule applies from the next run.
	if (!existed && mod.default !== undefined) {
		currentAgentExtensions.push(mod.default as KisoExtension);
	}
}

/**
 * W21 — the §3.5 fix-hint table: per speaker, the ONE-line path to stop
 * being asked. The hint names the FIX, never a bypass ("switch to
 * bypass" would be an approval-hole nudge — the R3 ruling). The
 * extension hint collapses the home prefix to ~ (the hint must stay
 * short enough for the one-row rule line at narrow widths).
 */
export function fixHintFor(speaker: string, tool: string): string | undefined {
	if (speaker === "mode:default") {
		if (tool === "shell") return undefined;
		return "/mode accept-edits auto-approves edits";
	}
	if (speaker === "mode:manual" || speaker === "mode:plan") return "/mode default";
	if (speaker === "mode:accept-edits" || speaker === "mode:bypass") return undefined;
	return `edit ${join(extensionsDir(), `${speaker}.mjs`).replace(homedir(), "~")}`;
}

/**
 * E3 — the project-level trust gate (ADR-0037): capability is trusted by
 * content digest, not by directory. Runs BEFORE any extension loads — the
 * mcp/skills merges must be in the env before the user-level extensions are
 * loaded (the mcp factory reads KISO_MCP_CONFIG at load time, the skills
 * extension scans KISO_SKILLS_DIR at load time).
 *
 * Verdicts: granted → load; refused → never load, never re-ask (refused is
 * sticky — re-evaluate by deleting the trust line or changing a file); no
 * record → only a HUMAN may decide, TTY only — non-TTY refuses with one
 * stderr line. Returns the artifacts on grant, null on anything else.
 */
export async function resolveProjectTrust(input: LineInput): Promise<ProjectArtifacts | null> {
	const artifacts = await projectArtifacts(process.cwd());
	if (artifacts === null) return null; // no .kiso artifacts — nothing to gate
	// merge round B: projectTrust "never" (user config) — the gate auto-refuses:
	// no ask, no record, nothing loads. There is deliberately no "always".
	if (resolveProjectTrustPolicy(loadUserConfig() ?? {}) === "never") {
		bodyLog(`[project .kiso] projectTrust: never — ${artifacts.root} not loaded`);
		return null;
	}
	const record = trustFor(artifacts.root, artifacts.digest);
	if (record?.decision === "granted") {
		applyProjectMerges(artifacts);
		return artifacts;
	}
	if (record?.decision === "refused") return null; // refused is sticky — no re-ask
	// First discovery — list every artifact (file name + digest short
	// prefix) and ask the human ONCE.
	if (!process.stdin.isTTY) {
		console.error(projectUntrustedNote(artifacts.files.length, artifacts.root));
		return null;
	}
	// v2c: the shared input (the editor on a TTY) reads the answer.
	// W21: the trust gate is the panel's SIMPLE flavor — the ruleOverride
	// carries the question, the args the artifact listing (the same rows
	// the bodyLog below records, verbatim — the listing still lands in
	// the scrollback; the panel is a bounded block, the record is not).
	bodyLog(`[project .kiso] ${artifacts.root}`);
	for (const row of projectTrustRows(artifacts.files, "  ")) bodyLog(row);
	const verdict = await askPanel(input, projectTrustView(artifacts.root, artifacts.files));
	// A cancel is a "no" HERE — refused is sticky, the project does not
	// load (re-evaluate by deleting the trust line or changing a file).
	// The non-TTY branch above returned WITHOUT a record so an interactive
	// run can still decide later.
	const granted = verdict.action === "allow";
	recordTrust({ root: artifacts.root, digest: artifacts.digest, decision: granted ? "granted" : "refused" });
	if (!granted) return null;
	applyProjectMerges(artifacts);
	return artifacts;
}

/**
 * E3 — merge the project's mcp.json and skills into the env BEFORE the
 * extension load. A server name in BOTH configs is a LOUD error (a silent
 * override would be a supply-chain surprise); a skill name in both merges
 * with project-wins and a stderr note. Exported for tests.
 */
export function applyProjectMerges(artifacts: ProjectArtifacts): void {
	if (artifacts.files.some((f) => f.kind === "mcp")) applyMcpMerge(artifacts.root);
	if (artifacts.files.some((f) => f.kind === "skill")) applySkillsMerge(artifacts.root);
}

/** Read an mcp.json with the mcp extension's tolerance: absent/unreadable →
 *  {}, present-but-broken → throw (the loader convention). */
function readMcpConfig(path: string): { mcpServers?: Record<string, unknown> } {
	let text: string;
	try {
		text = readFileSync(path, "utf8");
	} catch {
		return {};
	}
	let parsed: unknown;
	try {
		parsed = JSON.parse(text);
	} catch (err) {
		throw new Error(`[project .kiso] cannot parse ${path}: ${(err as Error).message}`);
	}
	if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
		throw new Error(`[project .kiso] ${path} must be an object with an mcpServers map`);
	}
	return parsed as { mcpServers?: Record<string, unknown> };
}

/** Merge user-level + project-level mcp.json into one temp file and point
 *  KISO_MCP_CONFIG at it — the mcp extension reads it at load time. */
function applyMcpMerge(root: string): void {
	const userPath = process.env.KISO_MCP_CONFIG ?? join(kisoHome(), "mcp.json");
	const user = readMcpConfig(userPath);
	const project = readMcpConfig(join(root, "mcp.json"));
	const userServers = user.mcpServers ?? {};
	const projectServers = project.mcpServers ?? {};
	if (Object.keys(projectServers).length === 0) return; // nothing to merge
	for (const name of Object.keys(projectServers)) {
		if (name in userServers) {
			throw new Error(`[project .kiso] mcp server "${name}" exists in both the user-level and the project-level mcp.json`);
		}
	}
	const merged = { mcpServers: { ...userServers, ...projectServers } };
	const temp = join(tmpdir(), `kiso-mcp-merged-${process.pid}.json`);
	writeFileSync(temp, `${JSON.stringify(merged, null, 2)}\n`, "utf8");
	process.env.KISO_MCP_CONFIG = temp;
	mergedTempPaths.push(temp);
}

/** Merge user-level + project-level skills into one temp scan dir (project
 *  skill dirs symlinked first; a name in both → project wins + a stderr
 *  note) and point KISO_SKILLS_DIR at it — the skills extension's existing
 *  scan reads it at load time and per read_skill call. */
function applySkillsMerge(root: string): void {
	const userDir = process.env.KISO_SKILLS_DIR ?? join(kisoHome(), "skills");
	const projectDir = join(root, "skills");
	const merged = mkdtempSync(join(tmpdir(), "kiso-skills-"));
	mergedTempPaths.push(merged);
	for (const dir of readdirSyncSafe(projectDir)) {
		symlinkSync(join(projectDir, dir), join(merged, dir)); // project wins on collision
	}
	for (const dir of readdirSyncSafe(userDir)) {
		const target = join(merged, dir);
		if (existsSync(target)) {
			console.error(`[project .kiso] skill "${dir}" exists in both user and project skills — project wins`);
			continue;
		}
		symlinkSync(join(userDir, dir), target);
	}
	process.env.KISO_SKILLS_DIR = merged;
}

function readdirSyncSafe(dir: string): string[] {
	try {
		return readdirSync(dir);
	} catch {
		return []; // no skills dir on either level = nothing to merge
	}
}

/** Decide every uncertain execution with the human — the panel's simple
 *  flavor: 1 Yes = rerun, 3 No = abandon; a cancel records NOTHING (the
 *  execution stays uncertain and durable — no rerun/abandoned is
 *  fabricated, round 10). The resolution feedback lands in the body —
 *  the body is the single stdout writer, never a stray console.log. */
export async function resolveUncertains(
	session: AgentSession,
	input: LineInput,
	isCancelled: () => boolean,
): Promise<void> {
	for (const uncertain of session.uncertainExecutions()) {
		const verdict = await askPanel(input, uncertainView(uncertain.name, uncertain.executionId));
		if (isCancelled() || verdict.action === "cancel") {
			// round 10: a cancellation NEVER records a verdict — the execution
			// stays uncertain and durable; no rerun/abandoned is fabricated.
			return;
		}
		const resolution = verdict.action === "allow" ? "rerun" : "abandoned";
		await session.resolveUncertain(uncertain.executionId, resolution);
		bodyLog(`  ${resolution}`);
	}
}
